name: CD - Deploy Go App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t chechnya-api:latest .

      - name: Save Docker image
        run: |
          docker save chechnya-api:latest -o chechnya-api.tar
          chmod 644 chechnya-api.tar  # <-- Ð”Ð¾Ð±Ð°Ð²Ð»ÑÐµÐ¼ Ð¿Ñ€Ð°Ð²Ð° Ð´Ð¾ÑÑ‚ÑƒÐ¿Ð°

      - name: Copy Docker image and configs to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "chechnya-api.tar,docker-compose.yml,.env,migrations"
          target: "/chechnya-product/"

      - name: Load Docker image & restart container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /chechnya-product

            echo "ðŸ“¦ Ð—Ð°Ð³Ñ€ÑƒÐ·ÐºÐ° Docker-Ð¾Ð±Ñ€Ð°Ð·Ð°..."
            docker load -i chechnya-api.tar

            echo "ðŸ” ÐŸÐµÑ€ÐµÐ·Ð°Ð¿ÑƒÑÐº ÐºÐ¾Ð½Ñ‚ÐµÐ¹Ð½ÐµÑ€Ð¾Ð²..."
            docker-compose down
            docker-compose up -d

            echo "âœ… Ð“Ð¾Ñ‚Ð¾Ð²Ð¾!"
